### ISSUE TITLE
What perl version will be used for running scripts?

### ISSUE THREAD

**Issue by bessarabov** [VadimPushtaev/YAPC_Russia_2015_perl_golf#3]

**Comment by VadimPushtaev** [comment]
5.10
I'll update the description.

**Comment by bessarabov** [comment]
There are 2 version of Perl 5.10 — 5.10.0 and 5.10.1. I hope that you will use 5.10.1, but I want to make sure. So, will it be 5.10.1?

**Comment by VadimPushtaev** [comment]
It will.
